// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxIdVICQXGfJ8MudqwgC2_VkgyCzCqwJw',
    appId: '1:230200917214:web:6cf141a85ae1380e4f964f',
    messagingSenderId: '230200917214',
    projectId: 'kinyalearn',
    authDomain: 'kinyalearn.firebaseapp.com',
    storageBucket: 'kinyalearn.firebasestorage.app',
    measurementId: 'G-MV502FGHQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxIdVICQXGfJ8MudqwgC2_VkgyCzCqwJw',
    appId: '1:230200917214:android:YOUR_ANDROID_APP_ID',
    messagingSenderId: '230200917214',
    projectId: 'kinyalearn',
    storageBucket: 'kinyalearn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxIdVICQXGfJ8MudqwgC2_VkgyCzCqwJw',
    appId: '1:230200917214:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '230200917214',
    projectId: 'kinyalearn',
    storageBucket: 'kinyalearn.firebasestorage.app',
    iosBundleId: 'com.kinyalearn.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxIdVICQXGfJ8MudqwgC2_VkgyCzCqwJw',
    appId: '1:230200917214:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '230200917214',
    projectId: 'kinyalearn',
    storageBucket: 'kinyalearn.firebasestorage.app',
    iosBundleId: 'com.kinyalearn.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxIdVICQXGfJ8MudqwgC2_VkgyCzCqwJw',
    appId: '1:230200917214:web:6cf141a85ae1380e4f964f',
    messagingSenderId: '230200917214',
    projectId: 'kinyalearn',
    authDomain: 'kinyalearn.firebaseapp.com',
    storageBucket: 'kinyalearn.firebasestorage.app',
  );
}
